### PR TITLE
Fix build by updating dependencies

### PR DESCRIPTION
**Pull request by barafael**
Hi, 

thanks for writing the awesome book!

I noticed these examples no longer build. Updating the dependencies did the trick (first commit). I also fixed 2 minor clippy warnings.
Should I open PRs for all the other branches?
Also, the code could use a RustFmt run, but I'm not sure you are ok with that. Let me know :)
Rafael

### CODE REVIEW

**Comment by jimblandy** [comment]
Hi! Thanks very much for the PR. Can you tell me more about exactly what goes wrong? Checking out the `rayon` branch and building works fine for me. I'm using 1.54.0.

**Comment by jimblandy** [comment]
The `cargo fmt` changes, I'm going to decline. Other projects that I contribute to require `cargo fmt`, and it's a good rule. But I don't think it's always ideal for presentation.

**Comment by barafael** [comment]
seems like I cannot reproduce it myself now? Never mind then...

**Comment by jimblandy** [comment]
Okay - glad to hear it!

**Pull request closed without merging**
